name: Configure Repository

on: [create]

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Set up teams
        run: |
          gh api -X PUT /orgs/dynamic-framework/teams/dynamic-framework-team/repos/${{ github.repository }} --field permission=push

      - name: Protect master branch
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/master/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": ["use-checks / Lint and Test", "use-pr-labeler / Labeling Job"]
            },
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 2
            },
            "restrictions": null,
            "required_conversation_resolution": true
          }'

      - name: Add repository secrets
        run: |
          gh secret set WIDGET_NAME_CATALOG --body "${{ github.repository | slug }}"
          gh secret set WIDGET_NAME_DEMO --body "${{ github.repository | slug }}"