name: Configure Repository

on:
  workflow_call:

permissions:
  contents: write
  actions: write

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Loading configuration
        run: |
          gh api -X GET "repos/${{ github.repository }}" --jq 'delete_branch_on_merge';

      - name: Enable auto-delete branches after merge
        run: |
          gh api -X PATCH /repos/${{ github.repository }} --raw-field 'delete_branch_on_merge=true' --silent

      - name: Protect master branch
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/master/protection \
          -d '{
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 2
            },
            "restrictions": null,
            "required_conversation_resolution": true
          }'

      - name: Create slug from repository name
        id: create_slug
        run: |
          repo_name=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')
          slug=$(echo "${repo_name}" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-')
          echo "slug=$slug" >> $GITHUB_ENV

      - name: Add repository secrets
        run: |
          gh secret set PROJECT_NAME --body "${slug}"
          gh secret set PROJECT_TOKEN --body "${{ secrets.MOCK_TOKEN }}"
          echo "My mock token: ${{ secrets.MOCK_TOKEN }}"
        env:
          slug: ${{ env.slug }}